version: '{build}'
skip_tags: true
skip_commits:
  message: /\[ci skip\]/
clone_depth: 10
install:
- git submodule update --init --recursive
- npm install -g grunt-cli bower
- npm install
- bower install
build_script:
- grunt